### ISSUE TITLE
method called with wrong name in examples/example_1/example_1.py

### ISSUE THREAD

**Issue by cclementi** [TensorDuck/pyfexd#1]
Hi Justin, 

I am trying to use your code, and in example_1.py at line 14 you call 
qcalc = obs.get_q_function()
I think there is a misspelling and this should be
qcalc = obs.get_q_functions() 

-Cecilia

**Comment by TensorDuck** [comment]
Apologies, it appears I deprecated the name and forgot to update the examples. I will update the examples right now. Thanks for bringing htis to my attention.
