### ISSUE TITLE
get_q_functions() called in the wrong way in pyfexd/examples/example_1/example_1.py

### ISSUE THREAD

**Issue by cclementi** [TensorDuck/pyfexd#2]
Hi Justin,

I think the way you call get_q_functions() at lines 18, 20, 22, 14 in pyfexd/examples/example_1/example_1.py is not correct. You have defined get_q_functions() as two functions, so either get_q_functions()[0] o get_q_functions()[1] should be called.
-Cecilia

Best,

**Comment by TensorDuck** [comment]
Yes, this appears to be the case, apologies. Thanks for bringing this bug to my attention and I will fix and push.
