### ISSUE TITLE
how do I install langevin_model package?

### ISSUE THREAD

**Issue by cclementi** [TensorDuck/pyfexd#3]
Hi Justin,

I am trying to run the example script pyfexd/examples/example_2/run.py, it requires to install the langevin_model package, I have cloned it but it doens't seem to be installed, at least there is no setup.py or similar installation script. 

Thanks,
-Cecilia

**Comment by TensorDuck** [comment]
There is no installation required. The package just needs to exist in your $PYTHONPATH variable. 

i.e.:
PYTHONPATH=/path/to/packages/:$PYTHONPATH
export PYTHONPATH

Where /path/to/packages/langevin_model is where the folder is cloned. I will update documentation to make this clear.
